<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IRF_Row1_Text</name>
   <tag></tag>
   <elementGuidId>b5bcbfa2-244f-48af-9cda-d9bc9ea32363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;inVildRatesTable&quot;]/tbody/tr[1]/td[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;inVildRatesTable&quot;]/tbody/tr[1]/td[5]/input</value>
   </webElementProperties>
</WebElementEntity>
