<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category-AusDropDown2</name>
   <tag></tag>
   <elementGuidId>572fa5ca-bf3b-4f6a-9869-b422cc2e0c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;collapseExample&quot;]/div/div[3]/div[2]/div/div/ul/li[4]/a/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;collapseExample&quot;]/div/div[3]/div[2]/div/div/ul/li[4]/a/label/input</value>
   </webElementProperties>
</WebElementEntity>
