<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Season-DropDown1</name>
   <tag></tag>
   <elementGuidId>91f0a429-f9f8-43c4-b4cd-73927bcc9c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;collapseExample&quot;]/div/div[3]/div[1]/div/div/ul/li[4]/a/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;collapseExample&quot;]/div/div[3]/div[1]/div/div/ul/li[4]/a/label/input</value>
   </webElementProperties>
</WebElementEntity>
