<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Row3_Cell1</name>
   <tag></tag>
   <elementGuidId>4e57769e-1fdd-460e-b5af-ef1cbe09aeee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;confirmDisplayTable&quot;]/tbody/tr[3]/td[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;confirmDisplayTable&quot;]/tbody/tr[3]/td[5]/input</value>
   </webElementProperties>
</WebElementEntity>
