<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Row3_Cell1</name>
   <tag></tag>
   <elementGuidId>bdd9d83d-661e-42af-a2a5-f4b367a44320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;confirmDisplayTable&quot;]/tbody/tr[3]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;confirmDisplayTable&quot;]/tbody/tr[3]/td[5]</value>
   </webElementProperties>
</WebElementEntity>
