<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Row2_Cell1</name>
   <tag></tag>
   <elementGuidId>3a089f0a-9f92-4bfd-922d-18b6bbfa87b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;confirmDisplayTable&quot;]/tbody/tr[2]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;confirmDisplayTable&quot;]/tbody/tr[2]/td[5]</value>
   </webElementProperties>
</WebElementEntity>
